### ISSUE TITLE
undefined is not an object (evaluating '_reactNavigation.ThemeColors.light')

### ISSUE THREAD

**Issue by WrathChaos** [react-navigation/tabs#164]
### Current behaviour

After upgraded react-navigation from v3 to v4, it just explodes. 

### Expected behaviour

Just navigate to screens

### Code sample

```
import { createBottomTabNavigator } from "react-navigation";
// Screens
import HomeScreen from "../../scenes/home/Home";
import TaskDetailsScreen from "../../scenes/task-details";

const defaultNavigationOptions = {
  tabBarVisible: false,
  header: null
};

export const Navigator = createBottomTabNavigator(
  {
    home: HomeScreen,
    taskDetails: TaskDetailsScreen
  },
  {
    defaultNavigationOptions
  }
);

```

### Screenshots (if applicable)

![Simulator Screen Shot - iPhone X - 2019-09-11 at 14 45 45](https://user-images.githubusercontent.com/6813862/64696750-e6e67280-d4a7-11e9-83a9-6949a6f62025.png)

### What have you tried

Tried to remove every cache, node_modules, package-lock.json etc but the problem still exists. 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | iOS 12.3
| react-native          | 0.60.5
| react-navigation-tabs | 2.4.1
| react-navigation | 4.0.2
| node                  | v10.15.3
| npm or yarn           | npm 6.10.3

**Comment by joegichuru** [comment]
experiencing the same

**Comment by Harkindey** [comment]
I have been experiencing this since Yesterday.

**Comment by WrathChaos** [comment]
Hi @satya164,
I've tried all of these. Cleaned the simulator's cache etc nothing fixed this problem. Could not update the v3 to v4.

**Comment by satya164** [comment]
Can you provide a runnable demo?

**Comment by WrathChaos** [comment]
Sure, let me create one

**Comment by WrathChaos** [comment]
@satya164 I have made the example repo. 
https://github.com/WrathChaos/react-navigation-tabs-error-example

FYI, I've tried the newest react-navigation v4 with a scratch project and it works well however updating from v3 to v4. It simply does not work and gives the error.

**Comment by WrathChaos** [comment]
@satya164 did you have a chance to look at? I really want to migrate v4

**Comment by jesperlindgren** [comment]
experiencing the same, anyone find a solution?

**Comment by dl-husky73** [comment]
I just upgraded from 3 to 4 and having the exact same issue.  Anyone make progress here?

**Comment by dl-husky73** [comment]
> @satya164 did you have a chance to look at? I really want to migrate v4

Can I ask why you closed this issue?   DId you resolve?

**Comment by WrathChaos** [comment]
Reopened it. I just re-wrote the whole navigation system with v4 again :( 
Could not migrate v3 to v4 also v5 is on the way :O Whole migration pain is on coming

**Comment by dl-husky73** [comment]
Thanks WrathChaos.  I followed this post https://github.com/react-navigation/tabs/issues/156 and resolved my issue.  
Basically, added experimentalImportSupport: true, in metro.config.js.
Then reset.
react-native start --reset-cache
watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && rm -rf /tmp/haste-map-react-native-package && npm cache clean --force && npm install
And then everything worked...
(Although sounds like you rewrote everything)

**Comment by JakeHadley** [comment]
I'm having this issue as well, the above solutions haven't worked for me.

**Comment by nar213** [comment]
I experience the above issue but only in my tests. 

```
    TypeError: Cannot read property 'light' of undefined

      at Object.<anonymous> (node_modules/react-navigation-tabs/lib/commonjs/views/BottomTabBar.tsx:450:19)
      at Object.<anonymous> (node_modules/react-navigation-tabs/lib/commonjs/navigators/createBottomTabNavigator.tsx:16:1)
```

I managed to resolve it by introducing a mock for `ThemeColors`.

```
export const ThemeColors = {
  light: { header: null },
  dark: { header: null },
};
```

I then subsequently hit the following issue

```
    TypeError: Cannot read property 'propTypes' of undefined

      at createAnimatedComponent (node_modules/react-native/Libraries/Animated/src/createAnimatedComponent.js:178:29)
      at Object.AnimatedImplementation.createAnimatedComponent (node_modules/react-native/jest/setup.js:143:19)
      at Object.BaseButton (node_modules/react-navigation-stack/lib/commonjs/views/BorderlessButton.tsx:5:61)
      at Object.<anonymous> (node_modules/react-navigation-stack/lib/commonjs/views/TouchableItem.tsx:19:1)
```

I haven't been able to find a way to reproduce it in a clean repository yet, so I have included below a simplified version of the code that is causing the issue.

CustomTabNavigator-test.js
```
import React from 'react';
import ShallowRenderer from 'react-test-renderer/shallow';

import { CustomTabNavigator } from '../../custom-navigators/CustomTabNavigator';

describe(CustomTabNavigator, () => {
  it('Broken Test', () => {
    const shallowRenderer = new ShallowRenderer();
    const tree = shallowRenderer.render(
      <CustomTabNavigator fetchProviders={jest.fn()} />
    );
    expect(tree).toMatchSnapshot();
  });
});
```

CustomTabNavigator.js
```
import PropTypes from 'prop-types';
import React from 'react';
import { createAppContainer } from 'react-navigation';
import { createMaterialTopTabNavigator } from 'react-navigation-tabs';

import TabA from './TabA';
import TabB from './TabB';
import requireAuth from '../guards/requireAuth';
import LoadingView from '../LoadingView';
import ErrorView from '../ui/ErrorView';

class CustomTabNavigator extends React.PureComponent {
  render() {
    const {
      error,
      hasTabA,
      hasTabB,
    } = this.props;

    if (error) {
      return <ErrorView details={error}/>;
    }

    const screens = {
    };

    if (hasTabA) {
      screens.tabA = {
        screen: requireAuth(TabA),
        navigationOptions: {
          title: 'TabA',
        },
      };
    }

    if (hasTabB) {
      screens.tabB = {
        screen: requireAuth(TabB),
        navigationOptions: {
          title: 'TabB',
        },
      };
    }

    const TabNavigator = createAppContainer(createMaterialTopTabNavigator(screens));

    return <TabNavigator detached={true} />;
  }
}

export { CustomTabNavigator };
```

package.json
```
...
    "react-native": "0.61.1",
...
    "react-navigation": "^3.13.0",
    "react-navigation-stack": "^1.9.3",
    "react-navigation-tabs": "^2.5.5",
...
  "jest": {
    "preset": "react-native",
    "moduleNameMapper": {
      "^image![a-zA-Z0-9$_-]+$": "GlobalImageStub",
      "^[@./a-zA-Z0-9$_-]+\\.(png|gif)$": "<rootDir>/node_modules/react-native/Libraries/Image/RelativeImageStub"
    },
    "modulePathIgnorePatterns": [
      "^[@./a-zA-Z0-9$_-]+\\.(png|gif)$"
    ],
    "setupFiles": [
      "<rootDir>/test-setup.js",
      "./node_modules/react-native-gesture-handler/jestSetup.js"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/enzyme-test-setup.js",
      "./node_modules/jest-enzyme/lib/index.js"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-navigation|smk|@react-native-community)"
    ],
    "transform": {
      "^.+\\.js$": "<rootDir>/preprocessor.js"
    }
  }

```

**Comment by satya164** [comment]
@nar213 please upgade react-navigation to 4.x

**Comment by nar213** [comment]
@satya164 Apologies typo, copied that from working branch, that error occurs in 4.0.10

**Comment by brentvatne** [comment]
delete your lockfile and node_modules and reinstall, you probably have an old version of some package like @react-navigation/core or @react-navigation/native somehow

**Comment by WrathChaos** [comment]
> delete your lockfile and node_modules and reinstall, you probably have an old version of some package like @react-navigation/core or @react-navigation/native somehow

Sorry but this does not work if you're trying to migrate from v3 to v4.

**Comment by nar213** [comment]
Cheers for the advice, followed those steps but this does not fix the issue. References to @react-navigation/core and @react-navigation/native in the lock file are 3.5.1 and 3.6.2 respectively, so don't think there's an issue of referencing an old version of dependencies 🤔

**Comment by Saad-Bashar** [comment]
just upgraded react-native to 0.59.10, did all steps like yarn cache clean, rm -rf node_modules, yarn install but still getting the same error. Using react navigation 3.0.0

**Comment by annygutierrez** [comment]
I have the same problem, I tried all the solutions, nothing works. 🤔

**Comment by jiangbophd** [comment]
still issue, already latest library

**Comment by RZsam** [comment]
TypeError: Cannot read property 'light' of undefined.
same problem here

**Comment by anishtr4** [comment]
Did anyone find any solution for this?

**Comment by brentvatne** [comment]
if you have this issue then you have some version of react-navigation-tabs that is incompatible with the react-navigation version that you are using. make sure you are using the latest version for whatever major version you're using and that your lockfiles aren't preventing that. feel free to share a reproducible example if you think you have found a situation where this is incorrect

**Comment by WrathChaos** [comment]
> if you have this issue then you have some version of react-navigation-tabs that is incompatible with the react-navigation version that you are using. make sure you are using the latest version for whatever major version you're using and that your lockfiles aren't preventing that. feel free to share a reproducible example if you think you have found a situation where this is incorrect

Actually I've already shared the reproducible example at the above posts.
Here you go:
https://github.com/WrathChaos/react-navigation-tabs-error-example

**Comment by brentvatne** [comment]
@WrathChaos - thanks, looking

**Comment by brentvatne** [comment]
@WrathChaos - wow there is a lot going on here... in the future please make a minimal example as per https://stackoverflow.com/help/mcve

**Comment by brentvatne** [comment]
@WrathChaos - the project does not build and run successfully. please make a minimal example with no extraneous code or dependencies and make sure it runs, see https://stackoverflow.com/help/mcve for more information on how to do that.

<img width="447" alt="Screen Shot 2019-10-10 at 13 53 47" src="https://user-images.githubusercontent.com/90494/66605859-b7d62600-eb65-11e9-937d-5a71a7c453b4.png">

**Comment by WrathChaos** [comment]
> @WrathChaos - wow there is a lot going on here... in the future please make a minimal example as per https://stackoverflow.com/help/mcve

Yes, sorry for the huge example. It just the exact example from the migration from v3 to v4. v4 itself just works perfectly, however, migration from v3 is seemed impossible.

**Comment by brentvatne** [comment]
sure. just let me know when you can create an example that reproduces the issue with the minimum amount of required dependencies and i can look into it. until then i maintain that the issue is a mismatch of versions and you need to ensure you're using the latest minor version of whatever major version of react-navigation libraries that you're using

**Comment by WrathChaos** [comment]
@brentvatne Actually I tried to fix the mismatch version but it simply does not fix for the migration. Actually I have no idea why React Navigation v4 is working but it does not work from migration.

**Comment by brentvatne** [comment]
i'll leave this open and if someone can share a minimal reproducible example i'd be very happy to look at it and provide a clear solution for everyone

**Comment by kashkama** [comment]
once I added and used the ```react-navigation-tabs``` the issue appeared. Maybe try removing that. For example, I was importing the ```createMaterialTopTabNavigator``` from ```react-navigation-tabs```, and the issue came about. I decide to import it from ```react-navigation```, and everything works.

**Comment by bmkopp10** [comment]
> once I added and used the `react-navigation-tabs` the issue appeared. Maybe try removing that. For example, I was importing the `createMaterialTopTabNavigator` from `react-navigation-tabs`, and the issue came about. I decide to import it from `react-navigation`, and everything works.

I was having the exact same problem.  This fixed it.  What are the differences between importing it from react-navigation vs react-navigation-tabs.  My only guess would be that react-navigation-tabs isn't typescript friendly as the error was a TypeError.

**Comment by cmacdonnacha** [comment]
If you are using Expo, running `expo start -c` fixed this for me.

**Comment by avz** [comment]
I fixed this issue by specifying the appropriate version of `react-navigation-tabs` (see rel notes https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0)
```
"react-navigation-tabs": "^1.2.0",
```

Newer versions of `react-native-tabs` cause an error.

**Comment by fxbayuanggara** [comment]
> have you tried deleting `node_modules` and `yarn.lock`/`package-lock.json` and running `yarn`/`npm install` again?
> 
> @brentvatne do you have any idea why this is happening? they seem to have latest versions of both react navigation and tabs which should always ensure that latest core and native are installed without having to delete `node_modules`

this works for me.

**Comment by ioness** [comment]
> > have you tried deleting `node_modules` and `yarn.lock`/`package-lock.json` and running `yarn`/`npm install` again?
> > @brentvatne do you have any idea why this is happening? they seem to have latest versions of both react navigation and tabs which should always ensure that latest core and native are installed without having to delete `node_modules`
> 
> this works for me.

Worked for me too.

**Comment by cahhvoy** [comment]
> Thanks WrathChaos. I followed this post #156 and resolved my issue.
> Basically, added experimentalImportSupport: true, in metro.config.js.
> Then reset.
> react-native start --reset-cache
> watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && rm -rf /tmp/haste-map-react-native-package && npm cache clean --force && npm install
> And then everything worked...
> (Although sounds like you rewrote everything)

This worked for me. I even din't have to reset or delete anything,  just set the 

**experimentalImportBundleSupport:  true** _//here//_  **metro-config/src/defaults/index.js**

stop dev' server and restart. Should Work

**Comment by j-avila** [comment]
any solution for this @brentvatne ?
I use the new react-navigation in an expo previous version (in the package.json have more details)
I got a light project to show sort of the problem 
https://github.com/j-avila/fakestagram.git

**Comment by brentvatne** [comment]
@j-avila in your project you're using react-navigation v4 and v5 libs in the same place.

remove these:

```
    "@react-navigation/core": "^5.0.0-alpha.24",
    "@react-navigation/stack": "^5.0.0-alpha.37",
```

**Comment by breim** [comment]
+1

**Comment by gerbus** [comment]
Just ran into this for a very different reason. Everything was working in both android and ios simulators, and then I did this:

`brew update`
`xcode-select --install`
`brew doctor`
`sudo mkdir -p /usr/local/Frameworks /usr/local/sbin`
`sudo chown -R $(whoami) /usr/local/Frameworks /usr/local/sbin`
`brew link python`
`brew cleanup`
`brew install watchman`

And then I get this same error. Clearly not an issue with node_modules or module versions.

**Comment by puhfista** [comment]
If you are like me, and in the very specific scenario where you have recently upgraded from v3 to v4, you can try using XCode to Clean Build. That fixed the issue for me on iOS.
